package be.kakumi.custommclauncher.utils;

import be.kakumi.custommclauncher.Config;
import fr.theshark34.openlauncherlib.FailException;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.util.Properties;

public class ConfigManager {

	private File file;
	private Properties properties;

	public ConfigManager(String name) {
		this.file = new File(Config.DIR, name+".properties");
		this.properties = new Properties();
		if(file.exists()) {
			load();
		}
	}

	public void put(String key, String value) {
		properties.setProperty(key, value);
		save();
	}

	public String get(String key) {
		return properties.getProperty(key);
	}

	public void save() {
		try {
			properties.store(new BufferedWriter(new FileWriter(file)), "Generated by " + Config.LAUNCHER_NAME);
		} catch (Throwable t) {
			throw new FailException("Can't save the properties", t);
		}
	}

	
	public void load() {
		try {
			properties.load(new FileInputStream(file));
		} catch (Throwable t) {
			throw new FailException("Can't load the properties", t);
		}
	}
}
